const AUTH = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    SET_USER: 'SET_USER',
    LOGOUT: 'USERS_LOGOUT',
}

const ALBUMS = {
    LOAD: 'ALBUMS_LOAD',
    LOAD_SUCCESS: 'ALBUMS_LOAD_SUCCESS',
    LOAD_FAIL: 'ALBUMS_LOAD_FAIL',
};

const PHOTOS = {
    LOAD: 'PHOTOS_LOAD',
    LOAD_SUCCESS: 'PHOTOS_LOAD_SUCCESS',
    LOAD_FAIL: 'PHOTOS_LOAD_FAIL',
};


export { AUTH, ALBUMS, PHOTOS };
