const ALBUMS = {
    LOAD: 'ALBUMS_LOAD',
    LOAD_SUCCESS: 'ALBUMS_LOAD_SUCCESS',
    LOAD_FAIL: 'ALBUMS_LOAD_FAIL',
};

const PHOTOS = {
    LOAD: 'PHOTOS_LOAD',
    LOAD_SUCCESS: 'PHOTOS_LOAD_SUCCESS',
    LOAD_FAIL: 'PHOTOS_LOAD_FAIL',
};

export { ALBUMS, PHOTOS };
